name: "フォークの自動更新"
on:
  schedule:
      #毎週日曜の午前2時(日本時間)に実行
    - cron:  '0 17 * * 6'
  workflow_dispatch:
  
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "上流からマージ"
        run: |
          #ユーザーの設定追加
          git config --global user.email "tkhs.right2008@gmail.com"
          git config --global user.name "UKON256"
          
          #フォーク元のURLを指定
          git remote add upstream https://github.com/ykundesu/SuperNewRoles.git
          git fetch upstream
          
          #制限を無視しすべてをフェッチ
          git pull --unshallow

          git checkout master
          git merge --no-edit upstream/master
          git push origin master
