name: "フォークの自動更新"
on:
  schedule:
      #毎週日曜の午前2時(UTC)に実行
    - cron:  '0 2 * * 0'
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'UKON256'

          #制限を無視しすべてをフェッチ
          git pull --unshallow

          #フォーク元のURLを指定
          git remote add upstream https://github.com/ykundesu/SuperNewRoles.git
          git fetch upstream
          
          git checkout -b feature/x origin/feature/x
          git merge --no-edit upstream/feature/x
          git push origin feature/x

          git checkout master
          git merge --no-edit upstream/master
          git push origin master
